
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
    async adapter() {
      if (process.env.NODE_ENV === "production") {
        const { PrismaNeon } = await import("@prisma/adapter-neon");
        const { Pool } = await import("@neondatabase/serverless");
        const pool = new Pool({ connectionString: process.env.DATABASE_URL });
        return new PrismaNeon(pool);
      } else {
        const { PrismaPg } = await import("@prisma/adapter-pg");
        const { Pool } = await import("pg");
        const pool = new Pool({ connectionString: process.env.DATABASE_URL });
        return new PrismaPg(pool);
      }
    },
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL || "postgresql://root:root@localhost:5432/acordio",
  },
});
